baseURL = 'http://blog.jodevsa.com/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "hugo-theme-monochrome"



[[menu.navbar]]
identifier = "posts"
name = "posts"
url = "/posts/"
weight = -100
