baseURL = 'http://blog.jodevsa.com/'
languageCode = 'en-us'
title = "Subhi's personal blog"
theme = "hugo-theme-monochrome"
publishDir = "./docs"



[[menu.navbar]]
identifier = "posts"
name = "posts"
url = "/posts/"
weight = -100
